### ISSUE TITLE
Add support for storage_type      = "gp3" for AWS RDS

### ISSUE THREAD

**Issue by YanRah** [terraform-aws-modules/terraform-aws-rds#442] opened 2022-11-10 07:19 UTC
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

**Comment by antonbabenko** [comment] 2022-11-10 07:40
Duplicate of #441

**Closed by antonbabenko** 2022-11-10 07:40 UTC

**Comment by YanRah** [comment] 2022-11-10 11:32
the provider supports the new attribute value but i am getting that when apply.

Error: expected storage_type to be one of [standard gp2 io1], got gp3
│
│ with module.ef-core.module.db.module.db_instance.aws_db_instance.this[0],
│ on .terraform/modules/ef-core.db/modules/db_instance/main.tf line 42, in resource "aws_db_instance" "this":
│ 42: storage_type = var.storage_type
