### ISSUE TITLE
snapshot_identifier default value causing validation conflict in aws provider 3.29

### ISSUE THREAD

**Issue by fractos** [terraform-aws-modules/terraform-aws-rds#291] opened 2021-02-20 10:02 UTC
As of yesterday, aws provider 3.29 now has validation on whether a username and a snapshot identifier are set. This appears to be sensitive to whether `null` or `""` is used. The default in this module is `""` which busts the validation.

This is currently being tracked in https://github.com/hashicorp/terraform-provider-aws/issues/17712

By way of mitigation, could we consider changing the default for `snapshot_identifier` to `null` ?

**Comment by mhoonjeon** [comment] 2021-02-21 06:39
I can confirm this is happening in my development settings too.

**Comment by aleon1220** [comment] 2021-02-22 01:44
is happenning to me now and i am on terraform cloud. I believe the conflict is in
the duplicate use of the var.snapshot_identifier

Take a look at line 63 and 139

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L139

**Comment by aleon1220** [comment] 2021-02-22 01:56
I think the majority of the community is tracking the issue at https://github.com/hashicorp/terraform-provider-aws/issues/17712

**Comment by bryantbiggs** [comment] 2021-02-22 19:01
hi all - can you re-check now since we have made the change to use `null` in #289

**Comment by evanstachowiak** [comment] 2021-02-22 19:27
The new version fixed it for me, @bryantbiggs

**Comment by bryantbiggs** [comment] 2021-02-22 19:29
thanks @evanstachowiak - closing this out for now but if there are any other issues, pleas feel free to open a new issue

**Closed by bryantbiggs** 2021-02-22 19:29 UTC

**Comment by fractos** [comment] 2021-03-01 12:49
@bryantbiggs Yep that's fixed it for us as well. Thanks!
