### ISSUE TITLE
Unable to find upgrade path

### ISSUE THREAD

**Issue by itd-seb** [terraform-aws-modules/terraform-aws-rds#385] opened 2022-02-21 15:31 UTC
## Description

While using AWS Provider 4.1 we do have this issue when restoring a database from snapshot.

## Versions
 - Terraform: 1.1.5
 - Provider(s): aws
 - Module: 4.1

## Reproduction
Restore database from snapshot when engine is set to 12.2

## Expected behavior
Restore from snapshot.

## Actual behavior
Breaks with following error and leaves RDS in tainted state

### Terminal Output Screenshot(s)
Error: error modifying DB Instance (xxx): InvalidParameterCombination: Cannot find upgrade path from 12.2.0.1.ru-2021-10.rur-2021-10.r1 to 12.2.

**Comment by bryantbiggs** [comment] 2022-02-22 00:28
this doesn't appear to be an issue related to the module but instead a restriction enforced by the AWS API - it looks like AWS is stating that there isn't an upgrade path from the source version to the dest version; you'll have to do intermediate upgrades (i.e. - making to large of a jump in upgrades *I think - issue lacks details). closing for now

**Closed by bryantbiggs** 2022-02-22 00:28 UTC
Labels: question

**Comment by itd-seb** [comment] 2022-02-22 07:50
There is no upgrade needed. DB is on 12.2 and statet version is also 12.2. In earlier versions of tf it did work without any problems

**Comment by bryantbiggs** [comment] 2022-02-22 11:57
> There is no upgrade needed. DB is on 12.2 and statet version is also 12.2. In earlier versions of the module it did work without any problems

well its not easy to see that without providing a proper reproduction/information

**Comment by itd-seb** [comment] 2022-02-22 14:19
We checked again today with different provider versions and for 3.74.3 to 4.2 it's always the same error.
What would you need for a proper reproduction?

**Comment by itd-seb** [comment] 2022-02-23 09:56
But you are right. AWS dropped support for any upgrade path coming from 12.2. So this is not a module issue. Thanks!
